### ISSUE TITLE
How does the image work with compose

### ISSUE THREAD

**Issue by asdfsx** [ContainerSolutions/zookeeper#3]
I have a question, how to set id/ip in docker-compose.yml
I want to use docker-compose to setup a simple zookeeper cluster in one server.

**Comment by thijsschnitger** [comment]
Hi there, thanks for checking it out!
I think that what you want cannot be achieved with docker-compose. You need to start the first container, and use the ip of that container as an argument when starting the consecutive containers. You can't do that with docker compose afaik.
